name: Round5-R5N1_1KEM_0d
type: kem
claimed-nist-level: 1
claimed-security: IND-CPA
length-public-key: 5214
length-ciphertext: 5236
length-secret-key: 16
length-shared-secret: 16
nistkat-sha256: e6dea6c9d7c98f452b430d77e3c3e04874a129e4ef90c7026ef57cf577fe4ada
principal-submitters:
  - Oscar Garcia-Morchon
implementations:
    - name: clean
      version: https://github.com/round5/code/commit/5e9002a5289659a3991321a27a4879c6e11d6fe7